(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"su3higgs-symmetric",
  Authors -> {"O. Gould", "P. Saffin"},
  Institutions -> {"U. Nottingham"},
  Emails -> {"oliver.gould@nottingham.ac.uk"},
  Date -> "November 16th, 2021"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Fundamental] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Adjoint] ] = NoUnfold[ Range[ 8 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Fundamental]},
    PropagatorLabel -> Phi,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

V[1] == {
    SelfConjugate -> True,
    Indices -> {Index[Adjoint]},
    PropagatorLabel -> A,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Adjoint]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> ghostA,
    PropagatorType -> U[1],
    PropagatorArrow -> Forward,
    Mass -> 0 }
}


(*        Definitions       *)

GaugeXi[ S[1] ] = 1;
GaugeXi[ V[1] ] = 0;

m[ ___ ] := m;


TheLabel[ S[1, {__}] ] := TheLabel[S[1]];
TheLabel[ V[1, {__}] ] := TheLabel[V[1]];
TheLabel[ U[1, {__}] ] := TheLabel[U[1]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ -U[1, {e1x1}] , U[1, {e2x1}] , V[1, {e3x2}] ] == {
{-(g*SUNF[e3x2, e1x1, e2x1]), 0},
{0, 0}
},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] ] == {
    {g*SUNF[e1x2, e2x2, e3x2], 0},
    {-(g*SUNF[e1x2, e2x2, e3x2]), 0},
    {-(g*SUNF[e1x2, e2x2, e3x2]), 0},
    {g*SUNF[e1x2, e2x2, e3x2], 0},
    {g*SUNF[e1x2, e2x2, e3x2], 0},
    {-(g*SUNF[e1x2, e2x2, e3x2]), 0}
},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] , V[1, {e4x2}] ] == {
    {I*g^2*(SUNF[e1x2, e2x2, Adjoint$1] SUNF[Adjoint$1, e3x2, e4x2] + SUNF[e1x2, e3x2, Adjoint$1] SUNF[Adjoint$1, e2x2, e4x2]), 0},
    {(-I)*g^2*(SUNF[e1x2, e2x2, Adjoint$1]SUNF[Adjoint$1, e3x2, e4x2] - SUNF[e1x2, e4x2, Adjoint$1]SUNF[Adjoint$1, e2x2, e3x2]), 0},
    {(-I)*g^2*(SUNF[e1x2, e3x2, Adjoint$1]SUNF[Adjoint$1, e2x2, e4x2] + SUNF[e1x2, e4x2, Adjoint$1]SUNF[Adjoint$1, e2x2, e3x2]), 0}
},

C[ S[1, {e1x1}] , S[1, {e2x1}] , -S[1, {e3x1}] , -S[1, {e4x1}] ] == {
    {(-2*I)*\[Lambda]*(SDF[e1x1, e4x1]*SDF[e2x1, e3x1] + SDF[e1x1, e3x1]*SDF[e2x1, e4x1]), 0}
},

C[ S[1, {e2x1}] , -S[1, {e3x1}] , V[1, {e1x2}] ] == {
    {I*g*SUNTF[{e1x2}, e3x1, e2x1], 0},
    {(-I)*g*SUNTF[{e1x2}, e3x1, e2x1], 0}
},

C[ S[1, {e3x1}] , -S[1, {e4x1}] , V[1, {e1x2}] , V[1, {e2x2}] ] == {
    {I*g^2*(
    SUNTF[{e2x2}, e4x1, Fundamental$1]*SUNTF[{e1x2}, Fundamental$1, e3x1] 
    +
    SUNTF[{e1x2}, e4x1, Fundamental$1]*SUNTF[{e2x2}, Fundamental$1, e3x1]), 0}
}

}
