(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"n-scalars",
  Authors -> {"O. Gould"},
  Institutions -> {"U. Nottingham"},
  Emails -> {"oliver.gould@nottingham.ac.uk"},
  Date -> "January 27th, 2025"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Flavour] ] = Range[ 5 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    PropagatorLabel -> Phi,
    SelfConjugate -> True,
    Indices -> {Index[Flavour]},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MassPhi }
}


(*        Definitions       *)


MassPhi[ ___ ] := MassPhi;


TheLabel[ S[1, {1}] ] := "Phi[1]"
TheLabel[ S[1, {2}] ] := "Phi[2]"
TheLabel[ S[1, {3}] ] := "Phi[3]"
TheLabel[ S[1, {4}] ] := "Phi[4]"
TheLabel[ S[1, {5}] ] := "Phi[5]"


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1, {e1x1}] , S[1, {e2x1}] , S[1, {e3x1}] ] == {{(-1/6*I)*(g[e1x1, e2x1, e3x1] + g[e1x1, e3x1, e2x1] + g[e2x1, e1x1, e3x1] + g[e2x1, e3x1, e1x1] + g[e3x1, e1x1, e2x1] + g[e3x1, e2x1, e1x1]), 0}},

C[ S[1, {e1x1}] , S[1, {e2x1}] , S[1, {e3x1}] , S[1, {e4x1}] ] == {{(-1/24*I)*(lam[e1x1, e2x1, e3x1, e4x1] + lam[e1x1, e2x1, e4x1, e3x1] + lam[e1x1, e3x1, e2x1, e4x1] + lam[e1x1, e3x1, e4x1, e2x1] + lam[e1x1, e4x1, e2x1, e3x1] + lam[e1x1, e4x1, e3x1, e2x1] + lam[e2x1, e1x1, e3x1, e4x1] + lam[e2x1, e1x1, e4x1, e3x1] + lam[e2x1, e3x1, e1x1, e4x1] + lam[e2x1, e3x1, e4x1, e1x1] + lam[e2x1, e4x1, e1x1, e3x1] + lam[e2x1, e4x1, e3x1, e1x1] + lam[e3x1, e1x1, e2x1, e4x1] + lam[e3x1, e1x1, e4x1, e2x1] + lam[e3x1, e2x1, e1x1, e4x1] + lam[e3x1, e2x1, e4x1, e1x1] + lam[e3x1, e4x1, e1x1, e2x1] + lam[e3x1, e4x1, e2x1, e1x1] + lam[e4x1, e1x1, e2x1, e3x1] + lam[e4x1, e1x1, e3x1, e2x1] + lam[e4x1, e2x1, e1x1, e3x1] + lam[e4x1, e2x1, e3x1, e1x1] + lam[e4x1, e3x1, e1x1, e2x1] + lam[e4x1, e3x1, e2x1, e1x1]), 0}}

}

