name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Release Asset
        run: |
          cp -r src WallGoMatrix
          zip WallGoMatrix_${tag}.zip WallGoMatrix/*
          tar -czf WallGoMatrix_${tag}.tar.gz WallGoMatrix/*
          rm -r WallGoMatrix
          ls -a

      - name: Upload Release Asset
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
