name: Release
on:
  push:
    tags:
      - "v*"
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the latest tag and date
        id: version_info
        run: |
          echo "tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV
          echo "date=$(date +"(%m-%d-%Y)")" >> $GITHUB_ENV

      - name: Update version and date in WallGoMatrix.m
        run: |
          sed -i.bak \
            -e "s/WallGoMatrix\\\$WallGoMatrixVersion = \".*\";/WallGoMatrix\\\$WallGoMatrixVersion = \"$tag\";/" \
            -e "s/WallGoMatrix\\\$WallGoMatrixVersionDate = \".*\";/WallGoMatrix\\\$WallGoMatrixVersionDate = \"$date\";/" \
            WallGoMatrix.m

      - name: Commit and push version update
        run: |
          git add WallGoMatrix.m
          git commit -m "Update WallGoMatrix version to ${{ env.tag }} and date to ${{ env.date }}"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release Asset
        run: |
          cp -r src WallGoMatrix
          zip WallGoMatrix_${{ github.ref_name }}.zip WallGoMatrix/*
          tar -czf WallGoMatrix_${{ github.ref_name }}.tar.gz WallGoMatrix/*
          rm -r WallGoMatrix
          ls -a

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./WallGoMatrix_${{ github.ref }}.zip
          asset_name: WallGoMatrix_${{ github.ref }}.zip
          asset_content_type: application/zip
